#!/bin/zsh

PORT=8001

last=${@: -1}
head=${@:1:-1}

cmd="$head"

if [ $last = "-i" ]
then
    eval $cmd
elif [ $last = "-w" ]
then
    eval "websocketd --port=$PORT --devconsole bash -c '$cmd'"
else
    echo "missing [-i | -w] flag"
fi
 
# bash -c $cmd
# echo $cmd
# eval "websocketd --port=$PORT --devconsole bash -c '$cmd'