#!/bin/zsh

PORT=8000

last=${@: -1}
head=${@:1:-1}

cmd="$head 2> >(~/wstd/exec/err) 1> >(~/wstd/exec/out)"

if [ $last = "-c" ]
then
    eval $cmd
elif [ $last = "-w" ]
then
    eval "websocketd --port=$PORT --devconsole bash -c '$cmd'"
else
    echo "missing [-c | -w] flag"
fi

# bash -c $cmd
# echo $cmd
# eval "websocketd --port=$PORT --devconsole bash -c '$cmd'"