class Tablook {

    // frink: [{"level":1,"header":"Interval Arithmetic","link":"https://tio.run/##ZUy7DsIwENvvKzyXa4ALbejQL0GHlIgMSG2HCkH@PpwYgwfL8qvWiBlb/uC5vfL@jstN2Cul1h04KEV08MYHpJ9O9PhfQ9zAsI/cZoFxdVaY3EVt2SFTaTu9sCiVu9DaRp5HpbM7HVcy1PoF"},{"level":1,"header":"Interval Arithmetic Example","link":"https://tio.run/##bY5NCsIwEIX3OcWQlSISsK6EuvMG7koLIZ3agSYNSVrw9DFpqag4q/n53psXoyKnJt2hQ6MQSsBZDhUZO4WK30xAB9/E2IEEb/s0XoDXNdPS@7@60CMsxyTJ/aeoJakxQ@WPvQBLzMmWpmz6xgSc2DwOk84Rz6JIFKxUU7AWjafwTJflnYCVZNaRCYOp@D193yDyKQEcYLctjlfgD6F0U/B9zVLF@AI"},{"level":1,"header":"Sample Calculations","link":"https://tio.run/##@/8/N7G4WCExL0WhLD@nNDeVy9BAIS01tUTB0AhCW0AoXTuF9MScnPy8Yi4jhRIgpaCvoIGutjyxJLVIE6QWxOXi4vr/HwA"},{"level":1,"header":"Liquor","link":"https://tio.run/##XY5BCsIwFAX3OcUjK12YmpYgLupdYviNLb9JCQ2Cl48NSKHuZ@a9Ut52pdRYdvEVWTyJEnroFgPHDzrVYqHkKKw4grP1Ic/QnTI7cXmg@mLKwTNNeXRUW@pmwOMmQ9@vWFKMAxqcDLxljuF84LeG/PWkMPuRf6TuSCFEKV8"},{"level":1,"header":"More Liquor","link":"https://tio.run/##bcxBCsIwFATQfU4xdNUubJIWtd14lxh/Vfz2lzRQ8PLRQAWF7gZm3qT0oCt2J3g3k1qzbTCwvFR5MLgIswtzpctctnWDiYKnMWJxkYJ27OUmXGVXrGOddfHhdd//HCz3kc4SIxNs@73ZhLb9l/a4N3gyOoMpiAxbSKmU3g"},{"level":1,"header":"Movie Magic","link":"https://tio.run/##@//fUN9EITc/Py83sbhYQV9Bw0TfWKEgU0HD1MBA30ghO1czzlhTQddOoTyxJLWIy10BXT1CnRFIWXpRYllmSSUXF9f//wA"},{"level":1,"header":"Fiscal Calculations","link":"https://tio.run/##@/8/qbQoryixJFXBVkFD2cjAwFDXwEzX2EBZQVcBxDXQNTTSNTZU1lTQV9DQsDAzsTAEypgYmhkYaiqUZOSXFifmpSik5OfkJBYVa3LBTdO1gwnqpyRWcoE1YKgHmomsQQmosliJC8UV2goEtXJxcf3/DwA"},{"level":1,"header":"Ouch!","link":"https://tio.run/##@//f1FAhvSgxt1ghxC9EQddOwdDCVKEgvzQvpRgkXpZZUqmQlppawoWuTqkkNbG4ID8/D6gusTg/JzMvVYmLi@v/fwA"},{"level":1,"header":"Microwave Cookery","link":"https://tio.run/##@//f0NDAQCFcwdhAoTg1WUFfQcPIXCG/SsFQITkxJ78oM1U/vSgxVz8lNd1ZU0HXTgHIcOPi4vr/HwA"},{"level":1,"header":"Why is Superman so Lazy?","link":"https://tio.run/##fY0xDsIwFEP3fwqPrRAiCURMcBSkqPy2GUii5JeK04cglrKwWfazXSu7LHOKK2dcUJbwlQd0JyT/Me6@yM30NMwuT5ydcAM3LW0wNmCb769YnUghA4kBZ4zMgim7p5dX2/5FCw/UGWOxgz7aHim20wJtlVL/mw8fFuFCRLW@AQ"},{"level":1,"header":"Fart Jokes","link":"https://tio.run/##lc2xCsIwGATgPU9xY4No04CCi0t3p85KwGCCaf6QPyJ9@li7CXVwPe67q7XTuz0ePlChyBjOA1o0B0zWZMYGR4wUi2OJ7QmOMttEL5vFP6w3gbK33N7MtA61UuqrtrhlbBVEU57ZhOvd8K/fOU4ezWx9lBct0anP5picEKLWNw"},{"level":1,"header":"Advanced Farting","link":"https://tio.run/##jY69CsIwFIX3PMUZq2KaRgrpoIubg1NfIOjFluanJFHo08e4iEvB6d7Lx/nuyXmQ5Cg8FhwhhRCwBjWsNzq8vHla@uzYoukwU7iRS@WQquUK06UujFlKg3b0l@XA5Y9GdWJNs8O31/6EszY@jBRZI3mLaTQ@eRfRX/vyparWoptC77qMolhIh8gYy/kN"},{"level":1,"header":"Days Old","link":"https://tio.run/##@/9f2dDSzFLXwELX0FJZQVvB0MjY0EQhJbGymAtNJrFUQV9Bw9JMz9xEITczJyczsSi5ODVZEyiazAWR1DM3NzJWgInr2inkZKZnlFSmJhYVc3Fx/f8PAA"},{"level":1,"header":"Model Solar System","link":"https://tio.run/##TY1BCoNADEX3niJLh6Jii5Qu2ouULsJMqoEaYTKef2rqIF0m7/3/c1aPH4I7EMY0RQy8KnRQX9oBWPxE6qp5WeQgu988Cv3BwJr@0ZsoVX17K4719det0P7OBIx@ZlnTlj/boSzPfaGry9IJrBXFk3tZJNAYiTTnLw"}]
    static tablook = {
        frink: [{"level":1,"header":"Interval Arithmetic","link":"#frink##ZUy7DsIwENvvKzyXa4ALbejQL0GHlIgMSG2HCkH@PpwYgwfL8qvWiBlb/uC5vfL@jstN2Cul1h04KEV08MYHpJ9O9PhfQ9zAsI/cZoFxdVaY3EVt2SFTaTu9sCiVu9DaRp5HpbM7HVcy1PoF"},{"level":1,"header":"Interval Arithmetic Example","link":"#frink##bY5NCsIwEIX3OcWQlSISsK6EuvMG7koLIZ3agSYNSVrw9DFpqag4q/n53psXoyKnJt2hQ6MQSsBZDhUZO4WK30xAB9/E2IEEb/s0XoDXNdPS@7@60CMsxyTJ/aeoJakxQ@WPvQBLzMmWpmz6xgSc2DwOk84Rz6JIFKxUU7AWjafwTJflnYCVZNaRCYOp@D193yDyKQEcYLctjlfgD6F0U/B9zVLF@AI"},{"level":1,"header":"Sample Calculations","link":"#frink##@/8/N7G4WCExL0WhLD@nNDeVy9BAIS01tUTB0AhCW0AoXTuF9MScnPy8Yi4jhRIgpaCvoIGutjyxJLVIE6QWxOXi4vr/HwA"},{"level":1,"header":"Liquor","link":"#frink##XY5BCsIwFAX3OcUjK12YmpYgLupdYviNLb9JCQ2Cl48NSKHuZ@a9Ut52pdRYdvEVWTyJEnroFgPHDzrVYqHkKKw4grP1Ic/QnTI7cXmg@mLKwTNNeXRUW@pmwOMmQ9@vWFKMAxqcDLxljuF84LeG/PWkMPuRf6TuSCFEKV8"},{"level":1,"header":"More Liquor","link":"#frink##bcxBCsIwFATQfU4xdNUubJIWtd14lxh/Vfz2lzRQ8PLRQAWF7gZm3qT0oCt2J3g3k1qzbTCwvFR5MLgIswtzpctctnWDiYKnMWJxkYJ27OUmXGVXrGOddfHhdd//HCz3kc4SIxNs@73ZhLb9l/a4N3gyOoMpiAxbSKmU3g"},{"level":1,"header":"Movie Magic","link":"#frink##@//fUN9EITc/Py83sbhYQV9Bw0TfWKEgU0HD1MBA30ghO1czzlhTQddOoTyxJLWIy10BXT1CnRFIWXpRYllmSSUXF9f//wA"},{"level":1,"header":"Fiscal Calculations","link":"#frink##@/8/qbQoryixJFXBVkFD2cjAwFDXwEzX2EBZQVcBxDXQNTTSNTZU1lTQV9DQsDAzsTAEypgYmhkYaiqUZOSXFifmpSik5OfkJBYVa3LBTdO1gwnqpyRWcoE1YKgHmomsQQmosliJC8UV2goEtXJxcf3/DwA"},{"level":1,"header":"Ouch!","link":"#frink##@//f1FAhvSgxt1ghxC9EQddOwdDCVKEgvzQvpRgkXpZZUqmQlppawoWuTqkkNbG4ID8/D6gusTg/JzMvVYmLi@v/fwA"},{"level":1,"header":"Microwave Cookery","link":"#frink##@//f0NDAQCFcwdhAoTg1WUFfQcPIXCG/SsFQITkxJ78oM1U/vSgxVz8lNd1ZU0HXTgHIcOPi4vr/HwA"},{"level":1,"header":"Why is Superman so Lazy?","link":"#frink##fY0xDsIwFEP3fwqPrRAiCURMcBSkqPy2GUii5JeK04cglrKwWfazXSu7LHOKK2dcUJbwlQd0JyT/Me6@yM30NMwuT5ydcAM3LW0wNmCb769YnUghA4kBZ4zMgim7p5dX2/5FCw/UGWOxgz7aHim20wJtlVL/mw8fFuFCRLW@AQ"},{"level":1,"header":"Fart Jokes","link":"#frink##lc2xCsIwGATgPU9xY4No04CCi0t3p85KwGCCaf6QPyJ9@li7CXVwPe67q7XTuz0ePlChyBjOA1o0B0zWZMYGR4wUi2OJ7QmOMttEL5vFP6w3gbK33N7MtA61UuqrtrhlbBVEU57ZhOvd8K/fOU4ezWx9lBct0anP5picEKLWNw"},{"level":1,"header":"Advanced Farting","link":"#frink##jY69CsIwFIX3PMUZq2KaRgrpoIubg1NfIOjFluanJFHo08e4iEvB6d7Lx/nuyXmQ5Cg8FhwhhRCwBjWsNzq8vHla@uzYoukwU7iRS@WQquUK06UujFlKg3b0l@XA5Y9GdWJNs8O31/6EszY@jBRZI3mLaTQ@eRfRX/vyparWoptC77qMolhIh8gYy/kN"},{"level":1,"header":"Days Old","link":"#frink##@/9f2dDSzFLXwELX0FJZQVvB0MjY0EQhJbGymAtNJrFUQV9Bw9JMz9xEITczJyczsSi5ODVZEyiazAWR1DM3NzJWgInr2inkZKZnlFSmJhYVc3Fx/f8PAA"},{"level":1,"header":"Model Solar System","link":"#frink##TY1BCoNADEX3niJLh6Jii5Qu2ouULsJMqoEaYTKef2rqIF0m7/3/c1aPH4I7EMY0RQy8KnRQX9oBWPxE6qp5WeQgu988Cv3BwJr@0ZsoVX17K4719det0P7OBIx@ZlnTlj/boSzPfaGry9IJrBXFk3tZJNAYiTTnLw"}]
    }

    static json2html(json) {
        let acc = "<ul class='tablook'>";
        let level = 1;
        for (let el of json) {
            if (el.level < level) {
                acc += "</ul>".repeat(level-el.level);
            }
            else if (el.level > level) {
                acc += "<ul class='tablook'>".repeat(el.level-level);
            }
            level = el.level;
            acc += `<li class='tablook'><a onclick='tablookItemClicked()' class='tablook' href=${el.link}>${el.header}</a></li>`;
        }
        return acc;
    }
}

// console.log(JSON.stringify(Tablook.tablook.frink))
